"""Build and run B1: first steady-state confined MODFLOW-2005 model.

Usage:
  python scripts/build_mf2005_01_confined.py
  python scripts/build_mf2005_01_confined.py --workspace C:/gw/b1
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import flopy
import matplotlib.pyplot as plt
import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = PROJECT_ROOT / "models" / "mf2005" / "01_confined_steady"
MODELNAME = "mf2005_01_confined"


def build_model(workspace: Path, modelname: str = MODELNAME) -> flopy.modflow.Modflow:
    """Create the B1 model instance with PM8-friendly package settings."""
    workspace.mkdir(parents=True, exist_ok=True)

    mf = flopy.modflow.Modflow(
        modelname=modelname,
        model_ws=str(workspace),
        exe_name="mf2005",
        version="mf2005",
    )

    nlay, nrow, ncol = 1, 10, 10

    # Explicit arrays are used (instead of CONSTANT shortcuts) for better PM8 DIS import compatibility.
    delr = np.full(ncol, 100.0, dtype=float)
    delc = np.full(nrow, 100.0, dtype=float)
    top = np.full((nrow, ncol), 10.0, dtype=float)
    botm = np.full((nlay, nrow, ncol), 0.0, dtype=float)

    flopy.modflow.ModflowDis(
        mf,
        nlay=nlay,
        nrow=nrow,
        ncol=ncol,
        nper=1,
        delr=delr,
        delc=delc,
        top=top,
        botm=botm,
        perlen=[1.0],
        nstp=[1],
        tsmult=[1.0],
        steady=[True],
        itmuni=4,
        lenuni=2,
    )

    ibound = np.ones((nlay, nrow, ncol), dtype=int)
    ibound[:, :, 0] = -1
    ibound[:, :, -1] = -1

    strt = np.zeros((nlay, nrow, ncol), dtype=float)
    strt[:, :, 0] = 10.0
    strt[:, :, -1] = 0.0

    # ifrefm=False -> fixed-format BAS file; often more robust for legacy PM8 converters.
    flopy.modflow.ModflowBas(mf, ibound=ibound, strt=strt, ifrefm=False)

    # Keep LPF simple for legacy PM8 converter compatibility (no DATA(BINARY) line).
    flopy.modflow.ModflowLpf(mf, hk=10.0, vka=10.0)
    flopy.modflow.ModflowPcg(mf)

    flopy.modflow.ModflowOc(
        mf,
        stress_period_data={(0, 0): ["save head", "print budget"]},
        compact=False,
    )

    return mf


def _compute_budget_residual_percent(lst_path: Path) -> float:
    """Read percent discrepancy from MODFLOW list budget (authoritative)."""
    list_budget = flopy.utils.MfListBudget(str(lst_path))
    incremental, _ = list_budget.get_dataframes(start_datetime="2000-01-01")
    return float(incremental["PERCENT_DISCREPANCY"].iloc[-1])


def _save_head_map(heads: np.ndarray, out_png: Path) -> None:
    fig, ax = plt.subplots(figsize=(6, 5), dpi=120)
    im = ax.imshow(heads[0], origin="upper", cmap="viridis")
    ax.set_title("B1 confined steady-state heads")
    ax.set_xlabel("Column")
    ax.set_ylabel("Row")
    fig.colorbar(im, ax=ax, label="Head")
    fig.tight_layout()
    fig.savefig(out_png)
    plt.close(fig)



def _write_pm8_dis_fallback(dis_path: Path, dataset1: str, period_line: str, style: str = "constant") -> None:
    """Write a handcrafted DIS file variant for PM8 converter fallbacks."""
    lines = [
        "# PM8 fallback DIS generated by build_mf2005_01_confined.py",
        dataset1,
        "0",
    ]

    if style == "constant":
        lines += [
            "CONSTANT 100.0",
            "CONSTANT 100.0",
            "CONSTANT 10.0",
            "CONSTANT 0.0",
        ]
    elif style == "internal_free":
        row100 = " ".join(["100.0"] * 10)
        row10 = " ".join(["10.0"] * 10)
        row0 = " ".join(["0.0"] * 10)
        lines += ["INTERNAL 1.0 (FREE)"] + [row100]
        lines += ["INTERNAL 1.0 (FREE)"] + [row100]
        lines += ["INTERNAL 1.0 (FREE)"] + [row10 for _ in range(10)]
        lines += ["INTERNAL 1.0 (FREE)"] + [row0 for _ in range(10)]
    else:
        raise ValueError(f"Unknown DIS fallback style: {style}")

    lines.append(period_line)
    dis_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _export_pm8_fallback_nams(workspace: Path, modelname: str) -> list[Path]:
    """Create several NAM+DIS fallback variants to handle PM8 parser differences."""
    variants = [
        ("pm8", "1 10 10 1 4 2", "1.0 1 1.0 SS", "constant"),
        ("pm8_u0", "1 10 10 1 0 0", "1.0 1 1.0 SS", "constant"),
        ("pm8_tr", "1 10 10 1 4 2", "1.0 1 1.0 TR", "constant"),
        ("pm8_num0", "1 10 10 1 4 2", "1.0 1 1.0 0", "constant"),
        ("pm8_num1", "1 10 10 1 4 2", "1.0 1 1.0 1", "constant"),
        ("pm8_full", "1 10 10 1 4 2", "1.0 1 1.0 SS", "internal_free"),
    ]

    fallback_nams: list[Path] = []
    for suffix, dataset1, period_line, style in variants:
        fallback_name = f"{modelname}_{suffix}"
        fallback_dis = workspace / f"{fallback_name}.dis"
        fallback_nam = workspace / f"{fallback_name}.nam"

        _write_pm8_dis_fallback(fallback_dis, dataset1, period_line, style=style)

        for ext in ("bas", "lpf", "pcg", "oc"):
            src = workspace / f"{modelname}.{ext}"
            dst = workspace / f"{fallback_name}.{ext}"
            if src.exists():
                shutil.copy2(src, dst)

        nam_lines = [
            "# PM8 fallback NAM",
            f"LIST 2 {fallback_name}.list",
            f"DIS 11 {fallback_name}.dis",
            f"BAS6 13 {fallback_name}.bas",
            f"LPF 15 {fallback_name}.lpf",
            f"PCG 27 {fallback_name}.pcg",
            f"OC 14 {fallback_name}.oc",
        ]
        fallback_nam.write_text("\n".join(nam_lines) + "\n", encoding="utf-8")
        fallback_nams.append(fallback_nam)

    return fallback_nams


def run_b1_model(workspace: Path = WORKSPACE, modelname: str = MODELNAME) -> dict[str, Path | float | None]:
    mf = build_model(workspace=workspace, modelname=modelname)
    mf.write_input()

    success, output = mf.run_model(silent=True, report=True)
    if not success:
        tail = "\n".join(output[-20:])
        raise RuntimeError(f"MODFLOW-2005 run failed. Output tail:\n{tail}")

    hds_path = workspace / f"{modelname}.hds"
    cbc_path = workspace / f"{modelname}.cbc"
    lst_path = workspace / f"{modelname}.list"
    nam_path = workspace / f"{modelname}.nam"
    png_path = workspace / "heads_map.png"
    summary_path = workspace / "run_summary.txt"
    fallback_nam_paths = _export_pm8_fallback_nams(workspace, modelname)

    heads = flopy.utils.HeadFile(str(hds_path)).get_data(kstpkper=(0, 0))
    residual_pct = _compute_budget_residual_percent(lst_path)
    _save_head_map(heads, png_path)

    left_mean = float(np.mean(heads[0, :, 0]))
    right_mean = float(np.mean(heads[0, :, -1]))

    summary_text = "\n".join(
        [
            "B1 first steady-state confined model (MODFLOW-2005)",
            f"Workspace: {workspace}",
            f"Name file for PM8 import: {nam_path}",
            f"Head left boundary mean: {left_mean:.4f}",
            f"Head right boundary mean: {right_mean:.4f}",
            f"Budget percent discrepancy (%): {residual_pct:.6f}",
            f"List file: {lst_path}",
            f"Head file: {hds_path}",
            f"Budget file: {cbc_path if cbc_path.exists() else 'not written (PM8-compat mode)'}",
            f"Head map: {png_path}",
            "PM8 fallback NAMs: " + ", ".join(str(p) for p in fallback_nam_paths),
            "PM8 tip: if conversion fails, retry from a short ASCII path like C:/gw/b1.",
        ]
    )
    summary_path.write_text(summary_text + "\n", encoding="utf-8")

    return {
        "workspace": workspace,
        "nam_path": nam_path,
        "hds_path": hds_path,
        "cbc_path": cbc_path if cbc_path.exists() else None,
        "lst_path": lst_path,
        "png_path": png_path,
        "summary_path": summary_path,
        "pm8_fallback_nams": fallback_nam_paths,
        "residual_pct": residual_pct,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--workspace",
        type=Path,
        default=WORKSPACE,
        help="Directory to write model files (for PM8 use short ASCII path).",
    )
    parser.add_argument("--modelname", default=MODELNAME)
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    result = run_b1_model(workspace=args.workspace, modelname=args.modelname)
    print("B1 model built and executed successfully.")
    print(f"Workspace: {result['workspace']}")
    print(f"PM8 import file (.nam): {result['nam_path']}")
    print(f"Budget residual (%): {result['residual_pct']:.6f}")
    print("PM8 fallback NAMs (.nam):")
    for p in result["pm8_fallback_nams"]:
        print(f"  - {p}")
    print("If PM8 conversion fails, rerun with --workspace C:/gw/b1 and import that .nam")
